services:
  - type: web
    name: guandan-backend
    env: python
    plan: free
    buildCommand: cd guandan-backend && pip install -r requirements.txt
    startCommand: cd guandan-backend && gunicorn app:app --worker-class eventlet -w 1 --bind 0.0.0.0:$PORT
    envVars:
      - key: FLASK_ENV
        value: production
